name: storklang
description: A statically-typed functional language by Amirbek Istamov 103536471
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  petitparser: ^5.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
